---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: php-fpm,  nginx_site_template: "symfony4-site.j2" }
    - { role: composer }
    - { role: ssh }
    - { role: neo4j }

# Other tasks
  tasks:
    - name: composer install
      shell: composer.phar install
      args:
        chdir: /vagrant/
        creates: vendor
